def calculate(x, y, epic):
    if epic == "add":
        return x + y
    elif epic == "subtract":
        return x - y
    elif epic == "multiply":
        return x * y
    elif epic == "divide":
        return x % y